### ISSUE TITLE
AppVeyor build broke again

### ISSUE THREAD

**Issue by mvmcjr** [EdonGashi/WpfMaterialForms#26]
@EdonGashi Hey, I think the appveyor nuget push broke again, could you check it out? Mind to add the appveyor.yaml to the project?

**Comment by edongashi** [comment]
I couldn't build locally either, it's giving some errors regarding .net standard or I'm not sure what it was

**Comment by mvmcjr** [comment]
@EdonGashi Hmm strange cause [AppVeyor built successfully](https://ci.appveyor.com/project/EdonGashi/wpfmaterialforms/build/2.0.0-ci101) but failed to publish the package. Can you post the build error?

###### Minor note: Do you have a slack, skype, discord or something that we can use to talk that is faster than GitHub? Not to be invasive or something, I understand that you are probably occupied but the thing is that GitHub doesn't notify me at all when someone replies.

**Comment by EdonGashi** [comment]
@redbaty good idea, look up `edongashiwow` on skype

**Comment by mvmcjr** [comment]
Fixed
