### ISSUE TITLE
Icon reverts to original colour when refocused while validation has not passed

### ISSUE THREAD

**Issue by rc201612** [EdonGashi/WpfMaterialForms#4]
Noticed the below on the Log In example.

Click "Log In" without populating any of the fields and observe the validation error.

![2016-12-25_19-20-11](https://cloud.githubusercontent.com/assets/18450631/21472529/3312f972-cad7-11e6-96c3-8ed25c49ae76.png)

Click back into the Username field and observe that the icon reverts to blue.

![2016-12-25_19-20-22](https://cloud.githubusercontent.com/assets/18450631/21472530/354b62ba-cad7-11e6-9c53-560b2ebf6df8.png)

Thanks,

**Comment by edongashi** [comment]
Thank you! Added 52e05d5 only for textboxes for now. I will update other controls when I have some free time. Also notice the validation template has a different background color which is annoying. If it's not updated from the toolkit we have to hack it manually.

**Comment by rc201612** [comment]
Great! Thanks! 

I really need to become more familiar with the toolkit.
