### ISSUE TITLE
Default Update trigger for Password fields

### ISSUE THREAD

**Issue by aalex675** [EdonGashi/WpfMaterialForms#6]
I have a dialog that shows a username and password when I type the username <TAB> Password <ENTER> the form is submitted with a blank password. This is caused by the default password binding being LostFocus. I think this should be changed to PropertyChanged like the TextBoxes.

**Comment by edongashi** [comment]
Changed it. Do you need a NuGet update or are you building from source?

**Comment by aalex675** [comment]
Could you update nuget?

**Comment by aalex675** [comment]
And thanks for changing it so quickly!

**Comment by edongashi** [comment]
I will once I finish work in ~2 hours. Lost touch with this old hardcoded mess.. I'm reworking it completely!

**Comment by edongashi** [comment]
I published 1.1.2 in NuGet. See if your issue has been resolved.

**Comment by aalex675** [comment]
Thanks, it is resolved. If you have a newer version that you are working on, I would be glad to lend a hand.

**Comment by edongashi** [comment]
See the development branch, I pushed more demos. Ideas are appreciated!
