### ISSUE TITLE
The type or namespace name 'Interactivity' does not exist in the namespace 'Microsoft.Expression' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by rc201612** [EdonGashi/WpfMaterialForms#9]
Hi,

I am getting the below error when I try to build master in VS 2107. Any idea what I could be missing?

The type or namespace name 'Interactivity' does not exist in the namespace 'Microsoft.Expression' (are you missing an assembly reference?)

Thanks.

**Comment by edongashi** [comment]
Seems like I'm referencing Expression Blend SDK somewhere. Haven't been aware of this though, maybe it's the MaterialForms.Demo or MaterialForms.Application? Those are for the demo and not part of the library.

I'll check it.

**Comment by edongashi** [comment]
It's the demo. Material.Application references Microsoft.Expression.Interactions, my suspicion is the fluid move behavior fix. Need to switch to NuGet packages for them. See if you can get it to work in the meantime by removing the reference and deleting those classes as they are not necessary.

Edit: Fixed it, merge latest commit and it should compile.

**Comment by rc201612** [comment]
That sorted it. Thanks.
